const API_BASE = '/api';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function apiFetch(path,options={}){const token=sessionStorage.getItem('bss_token');const headers={...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API_BASE+path,{...options,headers});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||j.message||'Request failed');return j}
function msg(id,t,c=''){const x=$('#'+id);if(x){x.textContent=t;x.className='message '+c}}
function fileData(f){return new Promise((res,rej)=>{if(!f||!f.size)return res(null);const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
document.addEventListener('DOMContentLoaded',()=>{
 const g=$('#grade'),s=$('#studyOption');if(g)g.onchange=()=>{const req=['11','12'].includes(g.value);if(s){s.disabled=!req;s.required=req;if(!req)s.value=''}};
 const af=$('#admissionForm');if(af)af.onsubmit=async e=>{e.preventDefault();const f=new FormData(af),a=Object.fromEntries(f.entries());if(!/^\d{16}$/.test(a.faydaId)||!/^\d{16}$/.test(a.guardianFaydaId))return msg('formMessage','Fayda ID must contain exactly 16 digits.','error');try{a.studentPhotoUrl=await fileData(f.get('studentPhoto'));a.guardianPhotoUrl=await fileData(f.get('guardianPhoto'));delete a.studentPhoto;delete a.guardianPhoto;const r=await apiFetch('/applications',{method:'POST',body:JSON.stringify(a)});msg('formMessage','Application submitted successfully. Application ID: '+r.applicationId+'. Status: Pending.','ok');af.reset();if(s){s.disabled=true;s.required=false}}catch(x){msg('formMessage',x.message,'error')}};
 const rf=$('#resultForm');if(rf)rf.onsubmit=async e=>{e.preventDefault();const box=$('#resultBox'),id=$('#studentId').value.trim();box.innerHTML='<div class="panel loading">Loading…</div>';try{const r=await apiFetch('/results/'+encodeURIComponent(id)),s=r.student,g=r.result;box.innerHTML='<div class="result-card"><div class="profile"><div class="avatar">'+(s.studentPhotoUrl?'<img src="'+esc(s.studentPhotoUrl)+'">':'<span>'+esc(s.fullName[0]||'S')+'</span>')+'</div><div><p class="eyebrow">Student Profile</p><h2>'+esc(s.fullName)+'</h2><p class="muted">'+esc(s.studentId)+' · Grade '+esc(s.grade)+' · '+esc(s.section)+(s.studyOption?' · '+esc(s.studyOption):'')+'</p></div></div><div class="result-grid"><div><span>Academic Year</span><b>'+esc(s.academicYear)+'</b></div><div><span>Gender</span><b>'+esc(s.gender)+'</b></div><div><span>Total</span><b>'+esc(g.total)+' / '+esc(g.maxTotal)+'</b></div><div><span>Average</span><b>'+esc(g.average)+'%</b></div></div><h3>Subjects & Marks</h3><div class="table-wrap"><table class="table"><tr><th>Subject</th><th>Mark</th><th>Maximum</th><th>Status</th></tr>'+g.subjects.map(x=>'<tr><td>'+esc(x.subjectName)+'</td><td>'+esc(x.mark)+'</td><td>'+esc(x.maximumMark)+'</td><td>'+esc(x.status)+'</td></tr>').join('')+'</table></div><div class="result-status '+esc(g.status.toLowerCase())+'">'+esc(g.status)+'</div><div class="profile-details"><div><h3>Student Address</h3><p>'+esc([s.country,s.region,s.city,s.woreda,s.subCityOrZone,s.kebele,s.specificAddress].filter(Boolean).join(', '))+'</p></div><div><h3>Guardian / Family</h3><p><b>'+esc(s.guardian.name)+'</b><br>'+esc(s.guardian.phone)+'</p></div></div></div>'}catch(x){box.innerHTML='<div class="panel"><p class="message error">'+esc(x.message||'Student ID not found.')+'</p></div>'}};
 const lf=$('#loginForm');if(lf)lf.onsubmit=async e=>{e.preventDefault();try{const r=await apiFetch('/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value.trim(),password:$('#password').value})});sessionStorage.setItem('bss_token',r.token);sessionStorage.setItem('bss_role',r.user.role);sessionStorage.setItem('bss_user',JSON.stringify(r.user));location.href='admin.html'}catch(x){msg('loginMessage',x.message,'error')}};
 if(location.pathname.endsWith('admin.html'))loadAdmin();
});
async function loadAdmin(){if(!sessionStorage.getItem('bss_token'))return location.href='login.html';try{const [a,s,sub]=await Promise.all([apiFetch('/applications'),apiFetch('/students'),apiFetch('/subjects')]);$('#appCount').textContent=a.length;$('#studentCount').textContent=s.length;$('#subjectCount').textContent=sub.length;$('#applicationsTable').innerHTML=a.length?'<div class="table-wrap"><table class="table"><tr><th>Applicant</th><th>Grade</th><th>Section</th><th>Phone</th><th>Status</th><th>Action</th></tr>'+a.map(x=>'<tr><td><b>'+esc([x.first_name,x.middle_name,x.last_name].filter(Boolean).join(' '))+'</b><small>'+esc(x.application_id)+'</small></td><td>'+esc(x.grade)+'</td><td>'+esc(x.section)+'</td><td>'+esc(x.phone)+'</td><td><span class="status">'+esc(x.status)+'</span></td><td>'+(x.status==='Pending'?'<button class="btn small" onclick="setApplicationStatus('+x.id+',\'Accepted\')">Accept</button> <button class="btn small danger" onclick="setApplicationStatus('+x.id+',\'Rejected\')">Reject</button>':esc(x.student_id||'—'))+'</td></tr>').join('')+'</table></div>':'<p class="muted">No applications yet.</p>';$('#studentsTable').innerHTML=s.length?'<div class="table-wrap"><table class="table"><tr><th>Student ID</th><th>Name</th><th>Grade</th><th>Section</th><th>Phone</th></tr>'+s.map(x=>'<tr><td><b>'+esc(x.student_id)+'</b></td><td>'+esc(x.full_name)+'</td><td>'+esc(x.grade)+'</td><td>'+esc(x.section)+'</td><td>'+esc(x.phone)+'</td></tr>').join('')+'</table></div>':'<p class="muted">No students yet.</p>';$('#subjectsTable').innerHTML=sub.length?'<div class="table-wrap"><table class="table"><tr><th>Grade</th><th>Section</th><th>Study Option</th><th>Subject</th><th>Max</th></tr>'+sub.map(x=>'<tr><td>'+x.grade+'</td><td>'+esc(x.section)+'</td><td>'+esc(x.study_option||'—')+'</td><td>'+esc(x.subject_name)+'</td><td>'+x.maximum_mark+'</td></tr>').join('')+'</table></div>':'<p class="muted">No subjects configured yet.</p>';const role=sessionStorage.getItem('bss_role');if($('#userRole'))$('#userRole').textContent=role.toUpperCase()}catch(x){if(x.message==='Unauthorized')location.href='login.html';else $('#applicationsTable').innerHTML='<p class="message error">'+esc(x.message)+'</p>'}}
async function setApplicationStatus(id,status){try{const r=await apiFetch('/applications/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})});alert(r.studentId?'Accepted. Student ID: '+r.studentId:'Application updated.');loadAdmin()}catch(x){alert(x.message)}}
async function loadMarks(){const id=$('#markStudentId').value.trim();try{const r=await apiFetch('/admin/results/'+encodeURIComponent(id));$('#marksBox').innerHTML='<h3>'+esc(r.student.full_name)+' · '+esc(r.student.student_id)+'</h3><div class="table-wrap"><table class="table"><tr><th>Subject</th><th>Maximum</th><th>Mark</th><th></th></tr>'+r.result.subjects.map(x=>'<tr><td>'+esc(x.subjectName)+'</td><td>'+x.maximumMark+'</td><td><input class="mark-input" id="mark-'+x.id+'" type="number" min="0" max="'+x.maximumMark+'" value="'+(x.status==='Not Graded'?'':x.mark)+'"></td><td><button class="btn small" onclick="saveMark(\''+esc(id)+'\','+x.id+')">Save</button></td></tr>').join('')+'</table></div><p id="marksMessage" class="message"></p>'}catch(x){$('#marksBox').innerHTML='<p class="message error">'+esc(x.message)+'</p>'}}
async function saveMark(studentId,subjectId){try{await apiFetch('/marks',{method:'POST',body:JSON.stringify({studentId,subjectId,mark:$('#mark-'+subjectId).value})});msg('marksMessage','Mark saved.','ok');loadMarks()}catch(x){msg('marksMessage',x.message,'error')}}
function logout(){sessionStorage.clear();location.href='login.html'}